export const GET_MENU_ITEMS_SUCCESS="GET_MENU_ITEMS_SUCCESS"     

export const CHANGE_CATEGORY="CHANGE_CATEGORY"

export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"

export const ADD_TO_CART= "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const REMOVE_1_FROM_CART = "REMOVE_1_FROM_CART"
export const GET_CART = "GET_CART"

export const ADD_TO_FAV= "ADD_TO_FAV"
export const REMOVE_FROM_FAV = "REMOVE_FROM_FAV"
export const GET_FAVS = "GET_FAVS"

export const LOGIN_SUCCESS= "LOGIN_SUCCESS"
export const LOGIN_FAIL= "LOGIN_FAIL"

export const LOGOUT_SUCCESS= "LOGOUT_SUCCESS"
export const LOGOUT_FAIL= "LOGOUT_FAIL"

export const GET_PROFILE= "GET_PROFILE"
export const DELETE_PROFILE= "DELETE_PROFILE"

export const LOADING_TRUE= "LOADING_TRUE"
export const LOADING_FALSE= "LOADING_FALSE"

export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"